# Generated by scripts/publish-cask.sh from scripts/cask/lumae.rb.in in the
# Lumae source repo. Edits here are overwritten by the next release.
cask "lumae" do
  version "0.7.0"
  sha256 "ecbc42af4ec547a882868b259916597c3723e4e731fa479e08b9c917131cca53"

  url "https://github.com/matlegault/lumae-releases/releases/download/v#{version}/Lumae-#{version}.dmg"
  name "Lumae"
  desc "Screen recorder and editor for software demos"
  homepage "https://github.com/matlegault/lumae-releases"

  livecheck do
    url "https://github.com/matlegault/lumae-releases/releases/latest/download/appcast.xml"
    # Sparkle's feed carries the build number beside the marketing version;
    # the download is named after the marketing version alone.
    strategy :sparkle, &:short_version
  end

  # Lumae updates itself through Sparkle, so `brew upgrade` leaves it alone
  # unless asked with --greedy; the feed above is the source of truth.
  auto_updates true
  depends_on macos: :tahoe

  app "Lumae.app"

  zap trash: [
    "~/Library/Caches/coderlife.Lumae",
    "~/Library/Containers/coderlife.Lumae",
    "~/Library/HTTPStorages/coderlife.Lumae",
  ]
end
